name: Build and Push Docker image to GHCR

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Luzid release version (e.g., v0.1.2)'
        required: true
        default: 'v0.1.2'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add support for more platforms with QEMU (optional)
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}
          ghcr.io/${{ github.repository }}:latest
        platforms: linux/amd64
        build-args: |
          LUZID_RELEASE=${{ github.event.inputs.tag }}
